# Neural Network from scratch

### Imports

In [8]:
from nn_from_scratch_classes import *

from nnfs.datasets import vertical_data

### Declare the data.

In [9]:
# Create dataset ( spiral gaussian data points )

X, y = vertical_data(samples=100, classes=3)

### Build up the neural network

The network below is made up of;

* 2 dense layers
* 2 Activation functions for those layers which are;
    * Softmax
    * ReLu


In [10]:
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)

# Create Softmax classifier’s combined loss and activation
loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

In [11]:
dense1.forward(X)

activation1.forward(dense1.output)

dense2.forward(activation1.output)

# Perform a forward pass through the activation/loss function
# takes the output of second dense layer here and returns loss
loss = loss_activation.forward(dense2.output, y)

### Calculate Accuracy of the network

In [12]:
# Let’s see output of the first few samples:
print(loss_activation.output[:5])

# Print loss value
print('loss:', loss)

[[0.33334524 0.33334319 0.33331157]
 [0.33334992 0.33334557 0.33330451]
 [0.33334725 0.33334346 0.33330929]
 [0.33335164 0.33334751 0.33330085]
 [0.33334958 0.33334626 0.33330417]]
loss: 1.0986000745614573


### Accuracy

In [13]:
# Calculate accuracy from output of activation2 and targets
# calculate values from first axis
predictions = np.argmax(loss_activation.output, axis=1)
if len(y.shape) == 2:
    y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)

In [14]:
# Print accuracy
print('acc:', accuracy)

acc: 0.3333333333333333


In [17]:
### Backward propagation

loss_activation.backward(loss_activation.output, y)
dense2.backward(loss_activation.dinputs)
activation1.backward(dense2.dinputs)
dense1.backward(activation1.dinputs)

### Print gradient weights and biases

In [18]:
# Print gradients
print(dense1.dweights)
print(dense1.dbiases)
print(dense2.dweights)
print(dense2.dbiases)

[[ 0.00018968  0.00011139 -0.00012938]
 [-0.00076709 -0.00093874 -0.00080369]]
[[-0.00162031 -0.00188332 -0.00158163]]
[[-4.39762490e-04  1.65757815e-04  2.74004674e-04]
 [-1.62675597e-04  8.11690003e-05  8.15065962e-05]
 [-9.84053544e-04  4.35968806e-04  5.48084738e-04]]
[[ 4.38696807e-06  2.92554748e-06 -7.31251555e-06]]
